spring:
  datasource:
    url: jdbc:h2:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #어플리케이션 실행시점에 테이블 drop 후 다시 생성
    properties:
      hibernate:
        #show_sql: true #System.out에 하이버네이트 실행 SQL을 남김
        format_sql : true

logging.level:
  org.hibernate.SQL: debug #Logger를 통해 하이버네이트 실행 SQL을 남김
  org.hibernate.type: trace